"""Initial_Schema_UUID

Revision ID: 60fba27fa72f
Revises: 
Create Date: 2025-12-15 17:56:05.501862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60fba27fa72f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smtp_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('encrypted_password', sa.String(), nullable=False),
    sa.Column('security', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smtp_accounts_id'), 'smtp_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_smtp_accounts_name'), 'smtp_accounts', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_smtp_accounts_name'), table_name='smtp_accounts')
    op.drop_index(op.f('ix_smtp_accounts_id'), table_name='smtp_accounts')
    op.drop_table('smtp_accounts')
    # ### end Alembic commands ###